name: Mirror GitHub Selected Repos to Gitee

on:
  push:
    branchs:
    - master
    schedule:
    # 每天上午七点定时同步（北京时间）
    - cron:  '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror Guanngxu's Github repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/Guanngxu
        dst: gitee/Guanngxu
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
        clone_style: ssh
        force_update: true
        debug: true
        # src_account_type: org
        # dst_account_type: org